// Generated by CoffeeScript 1.10.0
(function() {
  var responses, shakeEvent, stopShake;

  responses = ["Yes", "No", "Maybe", "Ask your mom", "Who knows?", "You have a slight chance", "I would go with what that voice in your head tells you to do", "Even Britney wouldn't attempt it", "What would Justin Beiber do?"];

  console.log('here');

  $("#kittyball").on('click', function() {
    var rand;
    $(".shake").effect("shake", {
      times: 4,
      direction: 'up'
    }, 2000);
    rand = Math.floor(Math.random() * responses.length);
    console.log(rand);
    console.log(responses[rand]);
    document.getElementById('response').innerHTML = 'Kitty Says: ' + responses[rand];
  });

  shakeEvent = new Shake({
    threshold: 15
  });

  stopShake = function() {
    shakeEvent.stop();
  };

  shakeEvent.start();

  window.addEventListener('shake', (function() {
    var randM;
    randM = Math.floor(Math.random() * responses.length);
    alert(responses[randM]);
  }), false);

  if (!('ondevicemotion' in window)) {
    alert('Not Supported');
  }

}).call(this);
